name: "Upload package.json SARIF"
# Run workflow each time code is pushed to your repository.
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
    security-events: write
  
jobs: 
  build:   
    runs-on: ubuntu-latest   
    steps:     
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master          
        continue-on-error: true              
        env:          
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}         
      - name: Upload SARIF file       
        uses: github/codeql-action/upload-sarif@v2       
        with:         
          sarif_file: snyk-sarif.json
          token: ${{ secrets.GITHUB_TOKEN }}
